// configuración sin .env - mala práctica


CLOUDINARY_CLOUD_NAME = 'dfx5nfqp9'
CLOUDINARY_CLOUD_API_KEY = '273466129374566'
CLOUDINARY_CLOUD_API_SECRET = '2pt2CP-GaNq-oxGCyUs5sU8dFNw'


module.exports = { CLOUDINARY_CLOUD_NAME, CLOUDINARY_CLOUD_API_KEY, CLOUDINARY_CLOUD_API_SECRET }