// configuración sin .env - mala práctica

const CLOUDINARY_CLOUD_NAME = ''
const CLOUDINARY_CLOUD_API_KEY = ''
const CLOUDINARY_CLOUD_API_SECRET = ''


module.exports = { CLOUDINARY_CLOUD_NAME, CLOUDINARY_CLOUD_API_KEY, CLOUDINARY_CLOUD_API_SECRET }